import React from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import Head from "next/head.js";
import Footer from "../../Components/footer";
import tachyons from "tachyons/css/tachyons.css";
import styles from "../../styles/Home.module.css";
import { useEffect, useState } from "react";
import { firebaseConfig } from "../../Components/firebaseConfig.js";
import { initializeApp } from "firebase/app";
import {
  getFirestore,
  collection,
  doc,
  addDoc,
  setDoc,
  getDoc,
  getDocs,
  query,
} from "firebase/firestore";

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Initialize Cloud Firestore and get a reference to the service
const db = getFirestore(app);

export default function NewsFetch({ Slug }) {
  async function getDocument() {
    // doc() getDoc()

    /// GET DOCUMENTS *
    const q = query(collection(db, "5FF_NEWS"));
    const Docs = await getDocs(q);
    //Result = [];
    Docs.forEach((doc) => {
      // console.log(doc.data())
      Result.push(doc.data());
    });

    try {
      Result.forEach((r) => {
        r.content = r.content.split("*");
      });
    } catch (e) {
      console.log(e);
    }

    setResult(await Result);
  }
  //let Result = [];
  const initValue = [{}];
  const [Result, setResulter] = useState([]);
  const [result, setResult] = useState(initValue);
  const [content, setContent] = useState([]);
  const router = useRouter();
  getDocument();

  useEffect(() => {}, [result]);

  return (
    <div>
      <Head className="ma0 pa0 mb0">
        <title>5 FORCE FIGHTERS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="ma0 pa0 fixed top-0 z-1">
        <nav
          className="fixed w-100 pa4-ns pv4 ph3 ma0 h2 top-0 flex items-center justify-between  bb b--pink "
          style={{ backgroundColor: "#1c0f1fdd" }}
        >
          <div className="w-60 ">
            <div className="flex ">
              <Link href="/">
                <h1 className="white f4 ba pa2 br2">
                  <span className="orange">5 </span>FORCE FIGHTERS
                </h1>
              </Link>
            </div>
          </div>
          <div className=" flex justify-center ">
            <Link href="../../">
              <h1 className="white f4 pa2 br2">HOME</h1>
            </Link>

            <Link href="../news">
              <h1 className="white f4 pa2 br2">NEWS</h1>
            </Link>
          </div>
        </nav>
      </header>

      <div className=" w-70 center pv4">
        <div className=" w-100 mt5 tc ">
          <div className="tl orange f4 ba w-10 pa3 ">
            <Link href="../news">{"<<back"}</Link>
          </div>
          <h2 className="pa0 f1-l f1-m f2 ma0 bb w-100 center pb4 white">
            5FF NEWS
          </h2>
        </div>

        {result.map((doc, index) => {
          if (doc.date == router.query.slug) {
            return (
              <div key={index} className="w-100  tc center  b--pink">
                <div className=" w-100 tc flex items-center ">
                  <h1 className="pa0 f2-l f3-m f3 ma0 bb w-100 center mb3 pv2">
                    {doc.title}
                  </h1>
                </div>

                {doc.img && (
                  <img
                    src={doc.img}
                    alt=""
                    style={{ width: "100%", height: "auto" }}
                  />
                )}

                <p>{doc.date}</p>

                {doc.content && (
                  <div>
                    <p className="tl">{doc.content[0]}</p>
                    <p className="tl">{doc.content[1]}</p>
                    <p className="tl">{doc.content[2]}</p>
                    <p className="tl">{doc.content[3]}</p>
                    <p className="tl">{doc.content[4]}</p>
                    <p className="tl">{doc.content[5]}</p>
                    <p className="tl">{doc.content[6]}</p>
                  </div>
                )}
              </div>
            );
          }
        })}
      </div>
      <div className="tl orange f4 mb3 w-70 center bb b--white-10 pv3">
        <Link href="../news" className="">
          {"<<back"}
        </Link>
      </div>
      <Footer />
    </div>
  );
}
