import Head from "next/head";
import Link from "next/link";
import style from "../styles/Home.module.css";
import tachyons from 'tachyons/css/tachyons.css'
import MainTop from "../Components/mainTop";
import PressKit from "../Components/pressKit"
import Characters from "../Components/characters";
import Features from "../Components/features";
import EmailList from "../Components/emailList";
import Footer from "../Components/footer";
export default function Home({ data }) {
  return (
    <div className="">
      <Head className="ma0 pa0 mb0">
        <title>5 FORCE FIGHTERS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="ma0 pa0 fixed top-0 z-2 ">
        <nav className={`nav_gradient fixed w-100  ph3 ma0 h2 top-0 flex items-center justify-between pv4 ${style.border_5ff} `}
        >
          <div className="w-60 ">
            <div className="flex ">
              <Link href="/">
                <h1 className="white f3-ns f5 ">
                  5 FORCE FIGHTERS
                </h1>
              </Link>
            </div>
          </div>
          
          <div className=" flex justify-center items-center">
            <Link href="./news">
                <p className="white f4-ns f5 pa2 br2 b">
                  News
                </p>
              </Link>
              <Link href="#">{/*steam url*/}
                <p className="white f4-ns f5 pa2 br2 b">
                  WishList
                </p>
              </Link>
          </div>
        </nav>
      </header>

      {/* CONTENT */}
      <main className="ma0 pa0">
      <MainTop/>
      <PressKit/>
      <Characters/>
      <Features/>
      <EmailList/>
      </main>
   
      <footer>
      <Footer/>
      </footer>
    </div>
  );
}